# Generated by Django 3.2.2 on 2021-05-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_teacher', models.CharField(max_length=100)),
                ('median_attn', models.CharField(max_length=200)),
                ('num_students', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(max_length=100)),
                ('gz_attn', models.CharField(max_length=100)),
                ('ps_attn', models.CharField(max_length=100)),
                ('sleep_n', models.CharField(max_length=100)),
                ('ov_attn', models.CharField(max_length=100)),
                ('n_q', models.CharField(max_length=100)),
                ('n_b', models.CharField(max_length=100)),
                ('n_p', models.CharField(max_length=100)),
                ('pos_attn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttentionID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(max_length=100)),
                ('session_teacher', models.CharField(max_length=100)),
                ('class_id', models.CharField(max_length=100)),
            ],
        ),
    ]
