# Generated by Django 3.2.3 on 2021-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattention',
            name='frame_counter',
            field=models.IntegerField(default=-1),
        ),
    ]
