# Generated by Django 3.2.3 on 2021-06-18 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0002_classattention_frame_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattention',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 19, 36, 21, 553215)),
        ),
        migrations.AddField(
            model_name='classattentionid',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
