# Generated by Django 3.2.3 on 2021-06-18 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0003_auto_20210618_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattention',
            name='hash_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.classattentionid'),
        ),
        migrations.AlterField(
            model_name='classattention',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 20, 35, 54, 696923)),
        ),
        migrations.AlterField(
            model_name='classattentionid',
            name='class_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
