# Generated by Django 3.2.3 on 2021-06-18 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0004_auto_20210618_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattention',
            name='time_elapsed',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='classattention',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 22, 45, 45, 122491)),
        ),
    ]
